from turtle import *
import time

def main():
    speed(8)
    setup(width=1000, height=1000)
    shape('triangle')
    pensize(3)
    pencolor('green')
    circle(200)
    color('green')
    penup()
    goto(-80, 240)
    pendown()
    
    pensize(1)
    fillcolor('red')
    begin_fill()
    circle(55)  
    end_fill()
    penup()
    goto(80, 240)  
    pendown()
    fillcolor('blue')
    begin_fill()
    circle(55)  
    end_fill()
    penup()
    goto(-100, 180)  
    pendown()
    fillcolor('yellow')
    begin_fill()
    for _ in range(2):
        forward(200)  
        right(90)
        forward(40)   
        right(90)
    end_fill()
    penup()
    goto(-50, 100)
    pencolor('black')
    pensize(20)
    pendown()
    right(60)      
    forward(120)    
    left(120)      
    forward(120)
    left(120)
    forward(120) 
    end_fill()
    
    
    hideturtle()

main()
